language: ruby
before_install:
  - rvm get head
services:
  - postgresql
sudo: false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
rvm:
  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
  - "2.1.3"
  - "2.1.4"
  - "2.1.5"
  - "2.1.6"
  - "2.1.7"
  - "2.1.8"
  - "2.1.9"
  - "2.2.0"
  - "2.2.1"
  - "2.2.2"
  - "2.2.3"
  - "2.2.4"
  - "2.2.5"
  - "2.2.6"
  - "2.3.0"
  - "2.3.1"
  - "2.3.2"
  - "2.3.3"
# uncomment this line if your project needs to run something other than `rake`:
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
